keys:
  - &users:
    - &rafael age1qruzj23k53mykd34jdj6lwf9snghxy9wnzzvpk4w8fud9p0y4stqpcmhqq
  - &hosts:
    - &aorus age10nxalwhup83s8x7pk20cs5cqf5ge336ddwh84zcvycq650hld52qrtu6xj
    - &elite age1tcarlg43cfxuu0daemmctvv08pdlwpa4xtc4z9gte0dy2zz97q4srglkz3
    - &one age18q7gkn6zcys47urf4jrpwjvfhhr2myep958vsvsnd2f0r00urf0qysjutn

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *rafael
      - *aorus
      - *elite
      - *one

